language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
sudo: false

before_script:
  - pip install unittest-data-provider
  - python setup.py install
script: cd test && python -m unittest
